name: Deploy SvelteKit to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # global install, zodat het niet steeds nodig is.
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          SVC_ID: ${{ secrets.SVC_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        # de logs zijn te zien in railway, dus daarom detatch
        run: railway up --service=${{ env.SVC_ID }} --detach
